version: '3'
services:

  accounts:
    image: pr03-account:1
    ports:
      - "8000:80"
    container_name: pr03-account
    hostname: account
    networks:
      - project03-overlay


  shop:
    image: pr03-shop:1
    ports:
      - "8001:80"
    container_name: pr03-shop
    hostname: shop
    networks:
      - project03-overlay


  order:
    image: pr03-order:1
    ports:
      - "8002:80"
    container_name: pr03-order
    hostname: order
    networks:
      - project03-overlay


  nginx:
    image: pr03-nginx:3
    ports:
      - "9999:80"
    container_name: pr03-nginx
    networks:
      - project03-overlay
    depends_on:
      - accounts
      - shop
      - order


  haproxy:
    image: pr03-haproxy:1
    ports:
      - "7777:80"
      - "8404:8404"
    container_name: pr03-haproxy
    networks:
      - project03-overlay

networks:
  project03-overlay:
    driver: overlay