version: '3'
services:

  accounts:
    image: bardiayaghmaie/pr04-account:1.0
    ports:
      - "8000:80"
    container_name: pr04-account
    hostname: account
    networks:
      - project04-overlay


  shop:
    image: bardiayaghmaie/pr04-shop:1.0
    ports:
      - "8001:80"
    container_name: pr04-shop
    hostname: shop
    networks:
      - project04-overlay


  order:
    image: bardiayaghmaie/pr04-order:1.0
    ports:
      - "8002:80"
    container_name: pr04-order
    hostname: order
    networks:
      - project04-overlay


  nginx:
    image: bardiayaghmaie/pr04-nginx:1.0
    ports:
      - "9999:80"
    container_name: pr04-nginx
    networks:
      - project04-overlay
    depends_on:
      - accounts
      - shop
      - order


  haproxy:
    image: bardiayaghmaie/pr04-haproxy:1.2
    ports:
      - "7777:80"
      - "8404:8404"
    container_name: pr04-haproxy
    
    networks:
      - project04-overlay
    depends_on:
      - nginx
    deploy:
      placement:
        constraints:
          - "node.hostname == DevSecOps"


networks:
  project04-overlay:
    driver: overlay